engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false

ratings:
  paths:
  - src/**/*.js

exclude_paths:
- src/cli.js
- test/**/*.js
- config/**/*.js
